<?php

namespace Database\Seeders;

use App\Models\CatalogoCampo;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CatalogoCampoSeeder extends Seeder
{
    public function run(): void
    {
        $campos = [

        [
            'nombre' => 'CURP',
            'slug' => 'curp',
            'tipo_campo' => 'curp',
            'validacion' => 'curp',
            'placeholder' => 'Ej. BEGP850101HNTXXX09',
            'ayuda' => null,
            'transformacion' => 'mayusculas',
            'autocomplete' => 'off',
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => 18,
            'longitud_maxima' => 18,
            'grupo_expediente' => 'datos',
        ],

        [
            'nombre' => 'RFC',
            'slug' => 'rfc',
            'tipo_campo' => 'rfc',
            'validacion' => 'rfc',
            'placeholder' => 'Ej. BEGP850101ABC',
            'ayuda' => null,
            'transformacion' => 'mayusculas',
            'autocomplete' => 'off',
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => 12,
            'longitud_maxima' => 13,
            'grupo_expediente' => 'datos',
        ],

        [
            'nombre' => 'NSS',
            'slug' => 'nss',
            'tipo_campo' => 'nss',
            'validacion' => 'nss',
            'placeholder' => 'Ej. 12345678901',
            'ayuda' => null,
            'transformacion' => null,
            'autocomplete' => 'off',
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => 11,
            'longitud_maxima' => 11,
            'grupo_expediente' => 'datos',
        ],

        [
            'nombre' => 'Correo electrónico',
            'slug' => 'correo',
            'tipo_campo' => 'email',
            'validacion' => 'email',
            'transformacion' => 'minusculas',
            'autocomplete' => 'email',
            'placeholder' => 'correo@ejemplo.com',
            'ayuda' => 'Opcional. También podremos enviarte avisos por este medio.',
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'grupo_expediente' => 'datos',
        ],

        [
            'nombre' => 'WhatsApp',
            'slug' => 'whatsapp',
            'tipo_campo' => 'tel',
            'validacion' => 'telefono',
            'transformacion' => null,
            'autocomplete' => 'tel',
            'placeholder' => 'Ej. 3111234567',
            'ayuda' => 'Lo utilizaremos para informarte sobre el avance de tu trámite.',
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'grupo_expediente' => 'datos',
        ],

        [
            'nombre' => 'Número de crédito INFONAVIT',
            'slug' => 'numero_de_credito_infonavit',
            'tipo_campo' => 'text',
            'validacion' => 'required',
            'placeholder' => 'Número de crédito INFONAVIT',
            'ayuda' => null,
            'transformacion' => 'mayusculas',
            'autocomplete' => 'off',
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => null,
            'longitud_maxima' => null,
            'grupo_expediente' => 'datos',
        ],

        [
            'nombre' => 'Código postal',
            'slug' => 'codigo_postal',
            'tipo_campo' => 'text',
            'validacion' => 'required',
            'placeholder' => 'Ej. 63000',
            'ayuda' => null,
            'transformacion' => null,
            'autocomplete' => 'postal-code',
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => 5,
            'longitud_maxima' => 5,
            'grupo_expediente' => 'datos',
        ],

        [
            'nombre' => 'Colonia',
            'slug' => 'colonia',
            'tipo_campo' => 'text',
            'validacion' => 'required',
            'placeholder' => 'Nombre de la colonia',
            'ayuda' => null,
            'transformacion' => 'mayusculas',
            'autocomplete' => 'address-level3',
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => null,
            'longitud_maxima' => null,
            'grupo_expediente' => 'datos',
        ],

        [
            'nombre' => 'Calle',
            'slug' => 'calle',
            'tipo_campo' => 'text',
            'validacion' => 'required',
            'placeholder' => 'Nombre de la calle',
            'ayuda' => null,
            'transformacion' => 'mayusculas',
            'autocomplete' => 'street-address',
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => null,
            'longitud_maxima' => null,
            'grupo_expediente' => 'datos',
        ],

        [
            'nombre' => 'Número exterior',
            'slug' => 'numero_exterior',
            'tipo_campo' => 'text',
            'validacion' => 'required',
            'placeholder' => 'Ej. 123',
            'ayuda' => null,
            'transformacion' => 'mayusculas',
            'autocomplete' => 'off',
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => null,
            'longitud_maxima' => null,
            'grupo_expediente' => 'datos',
        ],

        [
            'nombre' => 'Ciudad',
            'slug' => 'ciudad',
            'tipo_campo' => 'text',
            'validacion' => 'required',
            'placeholder' => 'Ej. Tepic',
            'ayuda' => null,
            'transformacion' => 'mayusculas',
            'autocomplete' => 'address-level2',
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => null,
            'longitud_maxima' => null,
            'grupo_expediente' => 'datos',
        ],

        [
            'nombre' => 'Estado',
            'slug' => 'estado',
            'tipo_campo' => 'select',
            'validacion' => 'required',
            'placeholder' => 'Selecciona tu estado',
            'ayuda' => null,
            'transformacion' => null,
            'autocomplete' => 'address-level1',
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => null,
            'longitud_maxima' => null,
            'grupo_expediente' => 'datos',

            'opciones' => [
                ['value' => 'AS', 'label' => 'Aguascalientes'],
                ['value' => 'BC', 'label' => 'Baja California'],
                ['value' => 'BS', 'label' => 'Baja California Sur'],
                ['value' => 'CC', 'label' => 'Campeche'],
                ['value' => 'CL', 'label' => 'Coahuila'],
                ['value' => 'CM', 'label' => 'Colima'],
                ['value' => 'CS', 'label' => 'Chiapas'],
                ['value' => 'CH', 'label' => 'Chihuahua'],
                ['value' => 'DF', 'label' => 'Ciudad de México'],
                ['value' => 'DG', 'label' => 'Durango'],
                ['value' => 'GT', 'label' => 'Guanajuato'],
                ['value' => 'GR', 'label' => 'Guerrero'],
                ['value' => 'HG', 'label' => 'Hidalgo'],
                ['value' => 'JC', 'label' => 'Jalisco'],
                ['value' => 'MC', 'label' => 'México'],
                ['value' => 'MN', 'label' => 'Michoacán'],
                ['value' => 'MS', 'label' => 'Morelos'],
                ['value' => 'NT', 'label' => 'Nayarit'],
                ['value' => 'NL', 'label' => 'Nuevo León'],
                ['value' => 'OC', 'label' => 'Oaxaca'],
                ['value' => 'PL', 'label' => 'Puebla'],
                ['value' => 'QT', 'label' => 'Querétaro'],
                ['value' => 'QR', 'label' => 'Quintana Roo'],
                ['value' => 'SP', 'label' => 'San Luis Potosí'],
                ['value' => 'SL', 'label' => 'Sinaloa'],
                ['value' => 'SR', 'label' => 'Sonora'],
                ['value' => 'TC', 'label' => 'Tabasco'],
                ['value' => 'TS', 'label' => 'Tamaulipas'],
                ['value' => 'TL', 'label' => 'Tlaxcala'],
                ['value' => 'VZ', 'label' => 'Veracruz'],
                ['value' => 'YN', 'label' => 'Yucatán'],
                ['value' => 'ZS', 'label' => 'Zacatecas'],
            ],
        ],
        [
            'nombre' => 'ID CIF',
            'slug' => 'id_cif',
            'tipo_campo' => 'text',
            'validacion' => null,
            'transformacion' => 'mayusculas',
            'autocomplete' => 'off',
            'placeholder' => 'Ej. A1B2C3D4E5',
            'ayuda' => 'Identificador que aparece en la Constancia de Situación Fiscal.',
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'grupo_expediente' => 'datos',
        ],
        [
            'nombre' => 'Constancia anterior',
            'slug' => 'constancia_anterior',
            'tipo_campo' => 'file',
            'validacion' => null,
            'transformacion' => null,
            'autocomplete' => null,
            'placeholder' => null,
            'ayuda' => 'Sube únicamente la primera página en PDF, imagen o captura. Debe verse claramente el RFC, ID CIF o el código QR.',
            'accept' => '.pdf,.jpg,.jpeg,.png',
            'tamano_maximo_mb' => 5,
            'multiple' => false,
            'grupo_expediente' => 'documentos',
        ],
        [
            'nombre' => 'Archivo .cer',
            'slug' => 'archivo_cer',
            'tipo_campo' => 'file',
            'validacion' => null,
            'transformacion' => null,
            'autocomplete' => null,
            'placeholder' => null,
            'ayuda' => 'Archivo .cer de tu e.firma.',
            'accept' => '.cer',
            'tamano_maximo_mb' => 2,
            'multiple' => false,
            'grupo_expediente' => 'credenciales',
        ],
        [
            'nombre' => 'Archivo .key',
            'slug' => 'archivo_key',
            'tipo_campo' => 'file',
            'validacion' => null,
            'transformacion' => null,
            'autocomplete' => null,
            'placeholder' => null,
            'ayuda' => 'Archivo .key de tu e.firma.',
            'accept' => '.key',
            'tamano_maximo_mb' => 2,
            'multiple' => false,
            'grupo_expediente' => 'credenciales',
        ],
        [
            'nombre' => 'Contraseña de la e.firma',
            'slug' => 'password_efirma',
            'tipo_campo' => 'password',
            'validacion' => null,
            'transformacion' => null,
            'autocomplete' => 'off',
            'placeholder' => 'Contraseña de tu llave privada',
            'ayuda' => 'Solo se utilizará para gestionar este trámite.',
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'grupo_expediente' => 'credenciales',
        ],
        [
            'nombre' => 'Autorizo el uso de mi e.firma',
            'slug' => 'autorizacion_efirma',
            'tipo_campo' => 'checkbox',
            'validacion' => 'accepted',
            'transformacion' => null,
            'autocomplete' => null,
            'placeholder' => null,
            'ayuda' => 'Autorizo expresamente a TramitaNet a utilizar mi e.firma únicamente para realizar el trámite solicitado.',
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'grupo_expediente' => 'credenciales',
        ],
        [
            'nombre' => 'Nombre como aparece en el recibo',
            'slug' => 'nombre_recibo',
            'tipo_campo' => 'text',
            'validacion' => 'required',
            'placeholder' => 'Nombre del titular',
            'transformacion' => 'mayusculas',
            'autocomplete' => 'name',
            'grupo_expediente' => 'datos',
        ],
        [
            'nombre' => 'Número de servicio CFE',
            'slug' => 'numero_servicio',
            'tipo_campo' => 'text',
            'validacion' => 'required',
            'placeholder' => 'Número de servicio',
            'transformacion' => null,
            'autocomplete' => 'off',
            'grupo_expediente' => 'datos',
        ],
        [
            'nombre' => 'Recibo anterior',
            'slug' => 'recibo_anterior',
            'tipo_campo' => 'file',
            'placeholder' => null,
            'ayuda' => 'Adjunta un recibo anterior en PDF o imagen.',
            'accept' => '.pdf,.jpg,.jpeg,.png',
            'tamano_maximo_mb' => 5,
            'multiple' => false,
            'grupo_expediente' => 'documentos',
        ],
        [
            'nombre' => 'Nombre(s)',
            'slug' => 'nombres',
            'tipo_campo' => 'text',
            'validacion' => null,
            'placeholder' => 'Escribe tu nombre o nombres',
            'ayuda' => 'Captura tu nombre exactamente como aparece en tu acta de nacimiento.',
            'transformacion' => null,
            'autocomplete' => null,
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => null,
            'longitud_maxima' => null,
            'grupo_expediente' => 'datos',
        ],
        [
            'nombre' => 'Apellido paterno',
            'slug' => 'apellido_paterno',
            'tipo_campo' => 'text',
            'validacion' => null,
            'placeholder' => 'Apellido paterno',
            'ayuda' => null,
            'transformacion' => null,
            'autocomplete' => null,
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => null,
            'longitud_maxima' => null,
            'grupo_expediente' => 'datos',
        ],
        [
            'nombre' => 'Apellido materno',
            'slug' => 'apellido_materno',
            'tipo_campo' => 'text',
            'validacion' => null,
            'placeholder' => 'Apellido materno',
            'ayuda' => null,
            'transformacion' => null,
            'autocomplete' => null,
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => null,
            'longitud_maxima' => null,
            'grupo_expediente' => 'datos',
        ],
        [
            'nombre' => 'Fecha de nacimiento',
            'slug' => 'fecha_nacimiento',
            'tipo_campo' => 'date',
            'validacion' => null,
            'placeholder' => null,
            'ayuda' => null,
            'transformacion' => null,
            'autocomplete' => null,
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => null,
            'longitud_maxima' => null,
            'grupo_expediente' => 'datos',
        ],
        [
            'nombre' => 'Sexo',
            'slug' => 'sexo',
            'tipo_campo' => 'select',
            'validacion' => null,
            'placeholder' => 'Selecciona una opción',
            'ayuda' => 'Debe coincidir con la información registrada en RENAPO.',
            'transformacion' => null,
            'autocomplete' => null,
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => null,
            'longitud_maxima' => null,
            'grupo_expediente' => 'datos',

            'opciones' => [
                'H' => 'Hombre',
                'M' => 'Mujer',
                "X" => "No binario",
            ],
        ],
        [
            'nombre' => 'Entidad federativa de nacimiento',
            'slug' => 'estado_nacimiento',
            'tipo_campo' => 'select',
            'validacion' => null,
            'placeholder' => 'Selecciona tu entidad de nacimiento',
            'ayuda' => 'Si naciste fuera de México selecciona "Nacido en el extranjero".',
            'transformacion' => null,
            'autocomplete' => null,
            'accept' => null,
            'tamano_maximo_mb' => null,
            'multiple' => false,
            'longitud_minima' => null,
            'longitud_maxima' => null,
            'grupo_expediente' => 'datos',

            'opciones' => [
                ['value' => 'AS', 'label' => 'Aguascalientes'],
                ['value' => 'BC', 'label' => 'Baja California'],
                ['value' => 'BS', 'label' => 'Baja California Sur'],
                ['value' => 'CC', 'label' => 'Campeche'],
                ['value' => 'CL', 'label' => 'Coahuila'],
                ['value' => 'CM', 'label' => 'Colima'],
                ['value' => 'CS', 'label' => 'Chiapas'],
                ['value' => 'CH', 'label' => 'Chihuahua'],
                ['value' => 'DF', 'label' => 'Ciudad de México'],
                ['value' => 'DG', 'label' => 'Durango'],
                ['value' => 'GT', 'label' => 'Guanajuato'],
                ['value' => 'GR', 'label' => 'Guerrero'],
                ['value' => 'HG', 'label' => 'Hidalgo'],
                ['value' => 'JC', 'label' => 'Jalisco'],
                ['value' => 'MC', 'label' => 'México'],
                ['value' => 'MN', 'label' => 'Michoacán'],
                ['value' => 'MS', 'label' => 'Morelos'],
                ['value' => 'NT', 'label' => 'Nayarit'],
                ['value' => 'NL', 'label' => 'Nuevo León'],
                ['value' => 'OC', 'label' => 'Oaxaca'],
                ['value' => 'PL', 'label' => 'Puebla'],
                ['value' => 'QT', 'label' => 'Querétaro'],
                ['value' => 'QR', 'label' => 'Quintana Roo'],
                ['value' => 'SP', 'label' => 'San Luis Potosí'],
                ['value' => 'SL', 'label' => 'Sinaloa'],
                ['value' => 'SR', 'label' => 'Sonora'],
                ['value' => 'TC', 'label' => 'Tabasco'],
                ['value' => 'TS', 'label' => 'Tamaulipas'],
                ['value' => 'TL', 'label' => 'Tlaxcala'],
                ['value' => 'VZ', 'label' => 'Veracruz'],
                ['value' => 'YN', 'label' => 'Yucatán'],
                ['value' => 'ZS', 'label' => 'Zacatecas'],
                ['value' => 'NE', 'label' => 'Nacido en el extranjero'],
            ],
        ],
        ];

        foreach ($campos as $campo) {
            CatalogoCampo::updateOrCreate(
                ['slug' => $campo['slug'] ?? Str::slug($campo['nombre'])],
                [
                    'nombre' => $campo['nombre'],
                    'slug' => $campo['slug'] ?? Str::slug($campo['nombre']),
                    'tipo_campo' => $campo['tipo_campo'] ?? $campo['tipo'] ?? 'text',
                    'validacion' => $campo['validacion'] ?? null,
                    'placeholder' => $campo['placeholder'] ?? null,
                    'ayuda' => $campo['ayuda'] ?? null,
                    'transformacion' => $campo['transformacion'] ?? null,
                    'autocomplete' => $campo['autocomplete'] ?? null,
                    'accept' => $campo['accept'] ?? null,
                    'tamano_maximo_mb' => $campo['tamano_maximo_mb'] ?? null,
                    'multiple' => $campo['multiple'] ?? false,
                    'longitud_minima' => $campo['longitud_minima'] ?? $campo['min'] ?? null,
                    'longitud_maxima' => $campo['longitud_maxima'] ?? $campo['max'] ?? null,
                    'activo' => true,
                    'grupo_expediente' => $campo['grupo_expediente'] ?? 'datos',
                    'opciones' => $campo['opciones'] ?? null,
                ]
            );
        }
    }
}
